### ISSUE TITLE
Errors when trying to stream

### ISSUE THREAD

**Issue by kvn1351** [sleeyax/stremio-streaming-server#11]
I'm getting this upon trying to stream something: 

```
-> GET /.git/config 
Error: Cannot parse path
    at openPath (/stremio/server.js:46331:8)
    at /stremio/server.js:46411:5
    at Layer.handle [as handle_request] (/stremio/server.js:122166:5)
    at next (/stremio/server.js:122399:13)
    at sendDLNAHeaders (/stremio/server.js:46521:15)
    at Layer.handle [as handle_request] (/stremio/server.js:122166:5)
    at next (/stremio/server.js:122399:13)
    at Route.dispatch (/stremio/server.js:122364:3)
    at handle (/stremio/server.js:121855:11)
    at Layer.handle [as handle_request] (/stremio/server.js:122166:5)
    at /stremio/server.js:121631:22
    at param (/stremio/server.js:121708:14)
    at param (/stremio/server.js:121719:14)
    at param (/stremio/server.js:121719:14)
    at Function.process_params (/stremio/server.js:121764:3)
    at next (/stremio/server.js:121625:10)

-> GET /?rest_route=/wp/v2/users/ 
-> GET /info.php 
-> GET /.DS_Store 
-> GET /telescope/requests 
Error: Cannot parse path
    at openPath (/stremio/server.js:46331:8)
    at /stremio/server.js:46411:5
    at Layer.handle [as handle_request] (/stremio/server.js:122166:5)
    at next (/stremio/server.js:122399:13)
    at sendDLNAHeaders (/stremio/server.js:46521:15)
    at Layer.handle [as handle_request] (/stremio/server.js:122166:5)
    at next (/stremio/server.js:122399:13)
    at Route.dispatch (/stremio/server.js:122364:3)
    at handle (/stremio/server.js:121855:11)
    at Layer.handle [as handle_request] (/stremio/server.js:122166:5)
    at /stremio/server.js:121631:22
    at param (/stremio/server.js:121708:14)
    at param (/stremio/server.js:121719:14)
    at param (/stremio/server.js:121719:14)
    at Function.process_params (/stremio/server.js:121764:3)
    at next (/stremio/server.js:121625:10)
-> GET /.env 

-> GET /.git/config 
Error: Cannot parse path
    at openPath (/stremio/server.js:46331:8)
    at /stremio/server.js:46411:5
    at Layer.handle [as handle_request] (/stremio/server.js:122166:5)
    at next (/stremio/server.js:122399:13)
    at sendDLNAHeaders (/stremio/server.js:46521:15)
    at Layer.handle [as handle_request] (/stremio/server.js:122166:5)
    at next (/stremio/server.js:122399:13)
    at Route.dispatch (/stremio/server.js:122364:3)
    at handle (/stremio/server.js:121855:11)
    at Layer.handle [as handle_request] (/stremio/server.js:122166:5)
    at /stremio/server.js:121631:22
    at param (/stremio/server.js:121708:14)
    at param (/stremio/server.js:121719:14)
    at param (/stremio/server.js:121719:14)
    at Function.process_params (/stremio/server.js:121764:3)
    at next (/stremio/server.js:121625:10)
-> GET /ecp/Current/exporttool/microsoft.exchange.ediscovery.exporttool.application 
-> GET /server-status 
-> GET /s/3134342e322e3130392e313635/_/;/META-INF/maven/com.atlassian.jira/jira-webapp-dist/pom.properties 
-> GET /config.json 
-> GET /login.action 
```

**Comment by sleeyax** [comment]
Uhh what are you trying to stream? According to the first line of the streaming server log it is looking for `/.git/config` and later on `/info.php`. these are odd paths and actually very concerning from a security standpoint.

**Comment by sleeyax** [comment]
So why was this closed? What was the issue and how did you solve it?

**Comment by kvn1351** [comment]
Sorry, it was due to an old version of torrentio. There haven't been any issues since I've updated. Sorry for wasting your time.
